### PR TITLE
support TSS 2.0

### LINKED ISSUE #15: Issues with TS 2.0?
Getting this in `:messages` when using with TypeScript@2:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 73, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 124, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/sources/typescript.py", line 139, in gather_candidates
[deoplete]     if (entry["kind"] != "warning"):
[deoplete] TypeError: string indices must be integers
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 73, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 124, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/sources/typescript.py", line 139, in gather_candidates
[deoplete]     if (entry["kind"] != "warning"):
[deoplete] TypeError: string indices must be integers
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 73, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 124, in gather_results
```

Haven't had a chance to start debugging.

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
Fix #15. deoplete-typescript will wait for the correct response.

I need to try more in real world since it might introduce concurrency problem. 

Anyone wants to try TS2 is welcomed to test this branch.

### CODE REVIEW

**Comment by faceleg** [comment]
I'll start using this branch tonight (+4 hours) and report any issues I find

**Comment by faceleg** [comment]
Ran it, got: 

```
[deoplete]   File "/Users/<username>/TEMP/deoplete-typescript/rplugin/python3/deoplete/sources/typescript.py", line 72, in _sendReuest
[deoplete]     key, value = headerline.split(":", 2)
[deoplete] ValueError: too many values to unpack (expected 2)
```

**Comment by HerringtonDarkholme** [comment]
I use TSS 2.0, installed by `typescript@beta`. What's your version?

**Comment by faceleg** [comment]
`typescript@2`

**Comment by HerringtonDarkholme** [comment]
Can you log `headerline`? I cannot reproduce this...

**Comment by faceleg** [comment]
```
2016-08-27 21:27:29,181 DEBUG    (deoplete.typescript) HEADERLINE: {"seq":0,"type":"response","command":"completions","request_seq":6,"success":true,"body":[{"name":"window","kind":"var","kindModifiers":"declare","sortText":"0"},{"name":"Window","kind":"interface","kindModifiers":"declare","sortText":"0"},{"name":"WindowBase64","kind":"interface","kindModifiers":"declare","sortText":"0"},{"name":"WindowConsole","kind":"interface","kindModifiers":"declare","sortText":"0"},{"name":"WindowLocalStorage","kind":"interface","kindModifiers":"declare","sortText":"0"},{"name":"WindowSessionStorage","kind":"interface","kindModifiers":"declare","sortText":"0"},{"name":"WindowTimers","kind":"interface","kindModifiers":"declare","sortText":"0"},{"name":"WindowTimersExtension","kind":"interface","kindModifiers":"declare","sortText":"0"}]}
```

**Comment by HerringtonDarkholme** [comment]
hmmmm... It seems response body is handled wrongly as header. But I have no idea why. Maybe `gather_completion` is called multiple times before last request is done.

**Comment by mhartington** [comment]
This appears to working with TS2.0 rather well so far. @faceleg is there any specific examples you have of it not working?

**Comment by faceleg** [comment]
Has worked well for me tonight

**Comment by mhartington** [comment]
Cool, @HerringtonDarkholme any reason to not merge this? In my tests so far, this has been working with both TS1.x and TS2.0

**Comment by HerringtonDarkholme** [comment]
I just think it need more test. Merging it when TS2.0 is officially announced?

**Comment by faceleg** [comment]
I use TS2 exclusively - personally I'd merge it right know 💃

**Comment by mhartington** [comment]
Hmm, yeah, I've been bouncing back and forth. I think we should merge it now and let people report any issues, if there are any.

**Comment by mhartington** [comment]
And we're merged 🎉

**Pull request merged**
