### PR TITLE
Add javascript support

### PR DESCRIPTION
**Pull request by DonnieWest**
If the user sets the variable g:typescript_tools_javascript to 1, javascript support is turned on

### CODE REVIEW

**Comment by DonnieWest** [comment]
I wasn't sure of the variable name or if this was the right way to grab the variable. When a user doesn't have the variable set, the eval throws an exception and I didn't see a way to pass eval a default variable value

**Comment by mhartington** [comment]
Thanks! Just tested this out, and it works great! I wonder if we should extract the variable into a actual viml file.
Similar here:
https://github.com/zchee/deoplete-jedi/blob/master/plugin/deoplete-jedi.vim 

Then instead of evals, we can just reference the variable directly.

**Comment by DonnieWest** [comment]
@mhartington that would make a lot more sense, thanks for the feedback! I'll try to push that up shortly

**Comment by DonnieWest** [comment]
@mhartington I changed the variable to more fit in with how other deoplete sources do it and added the viml file. It's much nicer :+1:

**Comment by mhartington** [comment]
Added via https://github.com/mhartington/deoplete-typescript/commit/7d6345630ae3e138f0e1e441184428a5b8758e8d

**Pull request closed without merging**
