### PR TITLE
Feature/tss neovim

### PR DESCRIPTION
**Pull request by faceleg**
Basic requirements for MVP

- [x] Instantiate tsserver
- [x] Cause tsserver to open current file
- [x] Send completion request to tsserver
- [x] Receive completion response from tsserver
- [x] Convert completion response into format deoplete expects and return

Required for actual use

- [ ] Make results contextual

Refactoring & improvements

- [ ] Look at making the TSServer class handle all communications instead of pasted code inside gather_candidates
- [ ] Delete dead code
- [ ] Clean up & move used classes to own files
- [ ] Call to get more details for results

References

 - https://github.com/Quramy/tsuquyomi/blob/master/autoload/tsuquyomi/tsClient.vim#L136
 - https://github.com/carlitux/deoplete-ternjs/blob/master/rplugin/python3/deoplete/sources/ternjs.py
 - https://github.com/Valloric/ycmd/blob/master/ycmd/completers/typescript/typescript_completer.py
 - https://github.com/carlitux/deoplete-ternjs/blob/master/tests/ternjs-deoplete.vim

### CODE REVIEW

**Comment by faceleg** [comment]
See #1

**Comment by mhartington** [comment]
How can I debug this/test that it's working? Is there a debug log setup?

**Comment by faceleg** [comment]
```Viml
  call dein#local('~/GitHub', {},['deoplete-typescript'])

  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_ignore_case = 1
  let g:deoplete#auto_complete_start_length = 0
  let g:auto_complete_start_length = 0
  let g:deoplete#enable_refresh_always = 1
  let g:deoplete#enable_debug = 1
  let g:deoplete#enable_profile = 1
  call deoplete#enable_logging('DEBUG', '/PATH_TO/deoplete.log')
```

`tail -f /PATH_TO/deoplete.log`

**Comment by faceleg** [comment]
At the moment it's just dumping whatever is available on the global scope (I think). Not sure how to make it contextual, have to leave off for awhile.

Let me know if you do some work on it?

**Comment by faceleg** [comment]
Also it's a mess, apologies.

**Comment by mhartington** [comment]
Hmm, can't get it work for some reason... it's not feed results back or logging them to the logfile

**Comment by Quramy** [comment]
Hi @faceleg .

It seems that you call tsserver's `open` command by every `gather_candidates` execution.  Why don't you use `reload` command?

**Comment by faceleg** [comment]
@Quramy I didn't know it existed! The only reference I've managed to find are the Tsuquyomi source, and this https://github.com/Microsoft/TypeScript/blob/2cb0dfd99dc2896958b75e44303d8a7a32e5dc33/src/server/protocol.d.ts

At the moment I'm just trying to get it working, there will be a lot of refactoring and optimisations to do after that

**Comment by faceleg** [comment]
@mhartington uh... I'm not sure, you are definitely editing a *.ts file? Checked out the correct branch?

**Comment by faceleg** [comment]
@mhartington you should see the following in your deoplete.log file after opening a file with neovim with the correct deoplete settings:

```
2016-05-12 14:38:40,132 INFO     (deoplete.logging) --- Deoplete Log Start ---
2016-05-12 14:38:40,132 INFO     (deoplete.logging) NVIM 0.1.3, Python 3.5.1, neovim client 0.1.8
```

**Comment by mhartington** [comment]
Yep, I'm seeing that in the log file, no error messages or completion menu.

https://youtu.be/EeSS3z7WFKo

**Comment by faceleg** [comment]
You've caught me just as I was about to get up and go to bed, hopefully inspiration strikes during my period of unconsciousness and I wake with better suggestions than I have now

**Comment by faceleg** [comment]
Python version? Mine is 3.5.1

**Comment by faceleg** [comment]
@mhartington I had a similar problem earlier, I restarted vim a few times and it resolved itself...

**Comment by mhartington** [comment]
Sweet, getting completion now. 
 https://youtu.be/wD-NHlA8PPU


seems a bit off though, it's pull from some methods, but not all methods related to that class.BTW,

**Comment by faceleg** [comment]
I saw that, thank you!

Yes it is completely useless at the moment, so far it only barely ticks the boxes I added in my original PR description.

I think its going to take stepping through the tsuquyomi code to learn exactly what is different about what this implementation is sending to tsserver compared to tsuquyomi's. Could be due to the fact that I'm calling "open" before each completion request, the current implementation is not optimal or even correct.

I couldn't get "nice" communication going, likely due to my toddler python skills. I'm not 100% sure that the "blocking" communications that are sort of working now can work long term, it won't if tsserver can respond to requests out of order.

**Comment by faceleg** [comment]
It works now, sometimes, added the `reload` usage as you suggested @Quramy, thanks!

I think it fails to complete currently because tsserver takes some time to return a result, which (I think) causes multiple requests to build up as deoplete triggers `gather_completions` with each keypress. The current implementation doesn't have any timeouts or async behaviour at all.

@Shougo what is the timeout for `gather_completions`? Do you know of other completions that have to deal with slow completion servers?

**Comment by Shougo** [comment]
@faceleg https://stackoverflow.com/questions/1191374/using-module-subprocess-with-timeout

You should not use read()/write().  It cannot set the timeout.

**Comment by mhartington** [comment]
New error has appeared. 

```
deoplete.typescript) {'seq': 0, 'command': 'completions', 'message': 'Error processing request. No Project.', 'request_seq': 9, 'type': 'response', 'success': False}
```

**Comment by mhartington** [comment]
Seems related to

https://github.com/faceleg/deoplete-typescript/commit/553c4c9c33d191d04b205ef0229b3fad4c29fc22

**Comment by faceleg** [comment]
Moved code into a PR off the same repo to make it easier for others to contribute

**Pull request closed without merging**
