### PR TITLE
Feature/tss2

### PR DESCRIPTION
**Pull request by faceleg**
Added a check for `{'reloadFinished': True}` responses, which *seems* to be the cause of the exceptions reported in #15

### CODE REVIEW

**Comment by faceleg** [comment]
Is TS1's "reload" call synchronous?

**Comment by mhartington** [comment]
Yeah, all of the commands are basically called synchronously

**Comment by faceleg** [comment]
I created this https://gitter.im/deoplete-typescript as I think a proper solution needs some more involved brainstorming that would just clutter up an issue comment thread

**Comment by mhartington** [comment]
Alright, started poking around in honest

So what I'm seeing in TS1.8 is this

```
2016-08-22 19:11:07,841 DEBUG    (deoplete.typescript) startig
2016-08-22 19:11:10,910 DEBUG    (deoplete.typescript) reload starting
2016-08-22 19:11:10,933 DEBUG    (deoplete.typescript) ************************
2016-08-22 19:11:10,933 DEBUG    (deoplete.typescript) reload done
2016-08-22 19:11:10,934 DEBUG    (deoplete.typescript) ************************
2016-08-22 19:11:11,145 DEBUG    (deoplete.typescript) request for completions
2016-08-22 19:11:11,145 DEBUG    (deoplete.typescript) ************************
2016-08-22 19:11:11,145 DEBUG    (deoplete.typescript) {'type': 'response', 'seq': 0, 'success': True, 'request_seq': 2, 'body': [{'kind': 'keyword', 'kindModifiers': '', 'sortText': '0', 'name': 'this'}, {'kind': 'keyword', 'kindModifiers': '', 'sortText': '0', 'name': 'throw'}], 'command': 'completions'}
2016-08-22 19:11:11,146 DEBUG    (deoplete.typescript) ************************
```

While TS2.0 debugs with this

```
2016-08-22 19:11:40,856 INFO     (deoplete.logging) NVIM v0.1.5-459-g7df9dd3, Python 3.5.2, neovim client 0.1.9
2016-08-22 19:11:42,882 DEBUG    (deoplete.typescript) startig
2016-08-22 19:11:44,449 DEBUG    (deoplete.typescript) reload starting
2016-08-22 19:11:46,141 DEBUG    (deoplete.typescript) ************************
2016-08-22 19:11:46,142 DEBUG    (deoplete.typescript) reload done
2016-08-22 19:11:46,142 DEBUG    (deoplete.typescript) ************************
2016-08-22 19:11:46,146 DEBUG    (deoplete.typescript) request for completions
2016-08-22 19:11:46,146 DEBUG    (deoplete.typescript) ************************
2016-08-22 19:11:46,147 DEBUG    (deoplete.typescript) {'command': 'reload', 'body': {'reloadFinished': True}, 'type': 'response', 'seq': 0, 'success': True, 'request_seq': 1}
2016-08-22 19:11:46,147 DEBUG    (deoplete.typescript) ************************
2016-08-22 19:11:46,147 DEBUG    (deoplete.typescript) data["body"] response contains reloadFinished
2016-08-22 19:11:46,147 DEBUG    (deoplete.typescript) ************************
2016-08-22 19:11:46,147 DEBUG    (deoplete.typescript) its a reload command
2016-08-22 19:11:46,147 DEBUG    (deoplete.typescript) ************************
2016-08-22 19:11:46,148 DEBUG    (deoplete.typescript) ignore?
2016-08-22 19:11:46,148 DEBUG    (deoplete.typescript) ************************
```

So we're getting two reload response, which makes sense with the new "reloadFinished" 
Looking at a reference point, [tsuquyomi](https://github.com/Quramy/tsuquyomi/commit/6e9bb5e258320638cd6ed9cf12cafe7520461dc0) seems to just ignore the second response. Which you were originally going for. 

So I'm wondering if we should just resend the same command again...

**Comment by faceleg** [comment]
Oh right, so you mean if we get an unexpected response. simply try again?

Anything to get it working in 2.0 - best is the enemy of good enough and all that.

**Comment by HerringtonDarkholme** [comment]
I have a simple fix. Just compare `request_seq` and `seq` and wait for the correct response.

**Comment by HerringtonDarkholme** [comment]
Hmm, it seems https://github.com/Microsoft/TypeScript/pull/8244 introduces this behavior.
I need to try out my fix more. I'm quite wary of concurrent requests... Waiting for correct `request_seq` might  trigger infinite loop.

**Comment by mhartington** [comment]
Closing.

**Pull request closed without merging**
